version: 2

models:
  - name: stg_sales__customers
    description: "Description des clients"
    columns:
      - name: customer_id
        description: 'Clés primaire de la table des clients'
        tests:
          - unique
          - not_null

  - name: stg_sales__orders
    description: "Description des commandes réalisées par les clients"
    columns:
     - name: order_id
       description: 'Clés primaire de la table des commandes'
       tests:
         - unique
         - not_null

     - name: customer_id
       description: "Clés étrangère des clients"
       tests:
         - relationships:
             arguments:
              name: customer_id_fk_stg_sales__customers
              to: ref('stg_sales__customers')
              field: customer_id

     - name: staff_id
       description: "Clés étrangère des vendeurs"
       tests:
         - relationships:
             arguments:
              name: staff_id_fk_stg_sales__staffs
              to: ref('stg_sales__staffs')
              field: staff_id

     - name: store_id
       description: "Clés étrangère des boutiques"
       tests:
         - relationships:
             arguments:
              name: store_id_fk_stg_sales__stores
              to: ref('stg_sales__stores')
              field: store_id

  - name: stg_sales__order_items
    description: "Détail des commandes réalisées par les clients à la granularité produit"
    columns:
     - name: sk_order_items
       description: 'Clés primaire de la table du détail des commandes'
       tests:
         - unique
         - not_null
     
     - name: product_id
       description: "Clés étrangère des produits"
       tests:
         - relationships:
             arguments:
              name: product_id_fk_stg_production__products
              to: ref('stg_production__products')
              field: product_id

  - name: stg_sales__staffs
    description: "Description du vendeur"
    columns:
     - name: staff_id
       description: 'Clés primaire de la table de description du vendeur'
       tests:
         - unique
         - not_null

     - name: store_id
       description: "Clés étrangère des boutiques"
       tests:
         - relationships:
             arguments:
              name: store_id_fk_stg_sales__stores
              to: ref('stg_sales__stores')
              field: store_id

  - name: stg_sales__stores
    description: "Description de la boutique dans laquelle a été réalisée la commande"
    columns:
     - name: store_id
       description: 'Clés primaire de la table de description du vendeur'
       tests:
         - unique
         - not_null